oc_core:
    resource: "@OCCoreBundle/Resources/config/routing.yml"
    prefix:   /

to_basics:
    resource: "@TOBasicsBundle/Resources/config/routing.yml"
    prefix:   /

toorm:
    resource: "@TOORMBundle/Resources/config/routing.yml"
    prefix:   /

oc_platform:
    resource: "@OCPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform