services:
#    oc_platform.example:
#        class: OC\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    oc_platform.antispam:
        class: OC\PlatformBundle\Services\Antispam\OCPlatformAntispamService
        arguments:
            - "@mailer"
            - "%locale%"
            - 50

    oc_platform.adverts:
        class: OC\PlatformBundle\Services\Adverts\OCPlatformAdvertsService

    oc_platform.email.application_mailer:
        class: OC\PlatformBundle\Email\ApplicationMailer
        arguments:
            - "@mailer"

    oc_platform.listener.application_creation:
        class: OC\PlatformBundle\Listener\ApplicationCreationListener
        arguments:
            - "@oc_platform.email.application_mailer"
        tags:
            - { name: doctrine.event_listener, event: postPersist }