services:
#    oc_platform.example:
#        class: OC\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    oc_platform.antispam:
        class: OC\PlatformBundle\Services\Antispam\OCPlatformAntispamService
        arguments:
            - "@mailer"
            - "%locale%"
            - 50
    oc_platform.adverts:
        class: OC\PlatformBundle\Services\Adverts\OCPlatformAdvertsService