<?php

namespace OC\PlatformBundle\Repository;

use TO\ORMBundle\Component\TOORMEntityRepository;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends TOORMEntityRepository
{

    protected $defaultAlias = 'a';

    public function loadApplicationsFromAdvert()
    {
        $this->loadRelatedFromEntity('applications', 'app', 'leftJoin');

        return $this;
    }

    public function loadCategoriesFromAdvert()
    {
        $this->loadRelatedFromEntity('categories', 'cat', 'leftJoin');

        return $this;
    }

    public function getAdvertsWithApplications()
    {

        $result = $this
            ->loadRelatedFromEntity('applications', 'app')
            ->getQueryBuilder()
            ->getQuery()
            ->getResult()
        ;

        return $result;
    }

    public function getAdvertsWithCategories(array $categories)
    {
        $criterias = [
            'cat.name IN :categories' => 'AND'
        ];
        $parameters = [
            'categories' => $categories
        ];
        $this
            ->loadRelatedFromEntity('categories', 'cat')
            ->findByFromQueryBuilder($criterias, $parameters)
        ;
    }

}
